## **Matrices**

In [1]:
import numpy as np


M1 = np.array(
    [
        [2, -5, -1, 0],
        [-9, 4, 6, 13],
        [4, 5, 12, -2]
    ]
)

In [2]:
## type
type(M1)

numpy.ndarray

In [3]:
## shape
M1.shape

(3, 4)

In [4]:
## M2 (4 x 2)

M2 = np.array(
    [
        [1,2],
        [3,4],
        [5,6],
        [7,8]
    ]
)

In [5]:
## multiply
M1.dot(M2)

array([[-18, -22],
       [124, 138],
       [ 65,  84]])

In [8]:
##
M3 = M1 @ M2

In [9]:
np.linalg.matrix_rank(M3)

np.int64(2)

In [10]:
M1

array([[ 2, -5, -1,  0],
       [-9,  4,  6, 13],
       [ 4,  5, 12, -2]])

In [11]:
np.linalg.matrix_rank(M1)

np.int64(3)

In [12]:
M1[0,:]

array([ 2, -5, -1,  0])