In [1]:
import numpy as np
import pandas as pd       ## based on numpy
import tensorflow as tf   ## based on numpy

In [2]:
## Read housing_data.csv
df = pd.read_csv('https://raw.githubusercontent.com/martinwg/ISA630/refs/heads/master/data/housing_data.csv')
df ## matrix

Bedrooms        Area  City_Distance  Age          Price
0            1   26.184098        1286.68   67   96004.804557
1            1   34.866901        1855.25   30   92473.722570
2            1   36.980709         692.09   24   98112.519940
3            1   17.445723        1399.49   66   92118.326874
4            1   52.587646          84.65    3   98976.653176
...        ...         ...            ...  ...            ...
4303         9  175.166533        1299.71    5  102707.356224
4304         6  215.352151        1346.36    5   99695.064992
4305         5  299.563972        1585.37    5   93803.715617
4306         1   29.193907        1896.23    2   92914.729126
4307         2   54.437573         255.24    0   93743.047290

[4308 rows x 5 columns]

In [3]:
## Retrieving a variable creates a vector
df.Age  ## vector

0       67
1       30
2       24
3       66
4        3
        ..
4303     5
4304     5
4305     5
4306     2
4307     0
Name: Age, Length: 4308, dtype: int64

## **Vectors**

In [4]:
## creating a vector in NumPy
v1 = np.array([3, 5, -2])

In [5]:
## shape of vector in NumPy
v1.shape

(3,)

In [7]:
## pandas Series are NumPy vector (.values)
df.Age.values

array([67, 30, 24, ...,  5,  2,  0])

In [8]:
## create a vector in Tensorflow
v1t = tf.constant([3, 5, -2])

In [9]:
v1t

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 3,  5, -2], dtype=int32)>

In [10]:
v1t.shape

TensorShape([3])

#### Vector Operations (+,-, scalar multiplication)

In [11]:
## dividing Area by 10 (scalar multiplication)
## multiplying 1/10
## (1/10) * df.Area
df.Area / 10

0        2.618410
1        3.486690
2        3.698071
3        1.744572
4        5.258765
          ...    
4303    17.516653
4304    21.535215
4305    29.956397
4306     2.919391
4307     5.443757
Name: Area, Length: 4308, dtype: float64

#### Vector Operations (transpose)

More computations than +,-, scalar multiplication

In [13]:
v1.T

array([ 3,  5, -2])

In [15]:
np.transpose(v1)

array([ 3,  5, -2])

In [14]:
tf.transpose(v1t)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 3,  5, -2], dtype=int32)>

#### Vector Operations (dot product)

In [16]:
v1

array([ 3,  5, -2])

In [17]:
v2 = np.array([6,4,3])

In [18]:
v1.shape, v2.shape

((3,), (3,))

In [19]:
## NumPy
np.dot(v1, v2)

32

In [ ]:
## NumPy Dot Product
v1.dot(v2)

In [20]:
df.Age.dot(df.Area)

24321483.918423787

In [21]:
## more computations (+, *)
## very high or very low

In [22]:
## exponential computation
## exp(v1) (each element of the vector gets exponential)

In [23]:
## exp(v1.dot(v1))
np.exp(df.Age.dot(df.Area))

<ipython-input-23-c5d0180e8b57>:2: RuntimeWarning: overflow encountered in exp
  np.exp(df.Age.dot(df.Area))


inf

In [24]:
## dot product v1 and v2
v1.dot(v2)

32

In [25]:
## L2 Norm (v1)
np.sqrt(v1.dot(v1))

6.164414002968976

In [26]:
## L2 Norm of v1
np.linalg.norm(v1, ord=2)

6.164414002968976

In [27]:
## Neural Network
## slopes = weights (notation for NNs)
## variables Age, Sqr Ft, Rooms, Bulbs
w = np.array([1.2, 20.1, 1000, 0.1 ])

In [29]:
## L2 Norm of the Vector w
## This penalty is ADDED to the SSE
np.linalg.norm(w, ord=2)

1000.2027094544385

In [30]:
w = np.array([0, 20.1, 1000, 0.1 ])

In [31]:
np.linalg.norm(w, ord=2)

1000.2019896001008

In [32]:
w = np.array([0, 20.1, 0, 0.1 ])

In [33]:
np.linalg.norm(w, ord=2)

20.10024875467963

In [34]:
## L1 Norm of v1
np.linalg.norm(v1, ord=1)

10.0