## **MATRIX ALGEBRA**

### **VECTORS**

In [ ]:
## libraries
import numpy as np
import tensorflow as tf

In [ ]:
## vector with NumPy
v1 = np.array([1,2,3,4])
v1 ## note this is either a column or a row vector

array([1, 2, 3, 4])

In [ ]:
## vector with Tensorflow
t1 = tf.constant([1,2,3,4])
t1

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
## vector addition
## NumPy
v2 = np.array([5,6,7,8])

v1+v2 ## conformable addition

array([ 6,  8, 10, 12])

In [ ]:
## scalar multiplication
## Tensorflow
2*t1

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 4, 6, 8], dtype=int32)>

In [ ]:
## Transpose
## NumPy
v1.T

array([1, 2, 3, 4])

In [ ]:
## Transpose
## Tensorflow
tf.transpose(t1)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
## dot product
print(v1)
print(v2)

v1.dot(v2)  ## note dot product of two vectors is a scalar

[1 2 3 4]
[5 6 7 8]


70

In [ ]:
## SQRFT
SQ = np.array([3000, 2000, 1500])
SQ.dot(SQ)

15250000

In [ ]:
## L2 NORM
## This is the distance from the vector to the vector 0
## L2 norm is a scalar
w = np.array([0.44, 2.83, -0.01]) ## slopes

In [ ]:
np.sqrt(0.44**2 + 2.83**2 + (-0.01)**2)

2.8640181563670297

In [ ]:
np.linalg.norm(w, ord = 2)

2.8640181563670297

In [ ]:
w = np.array([10000, 2.83, 5]) ## slopes
np.linalg.norm(w) ## this is a penalty

10000.001650444863

L2 Norm

* Tends to make slopes (weight vector) close to zero
* penalizes the algorithm for large slopes
* If variable is NOT important, the L2 norm will try to make the weight close to zero

In [ ]:
w1 = tf.constant([0.44, 2.873, -0.01])
tf.norm(w1, ord = 1)

<tf.Tensor: shape=(), dtype=float32, numpy=3.323>

In [ ]:
0.44 + 2.873+ 0.01

3.323

**L1 NORM**

* Tries to make non-important weight (slopes) exactly zero (fewer computations)
* Disadvantage: in math we don't like absolute values

In [ ]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(penalty = 'l2')

In [ ]:
from sklearn.neural_network import MLPClassifier

nn = MLPClassifier()

### **Matrices**

In [ ]:
M1 = np.array([[2, -5, -11, 0],
               [-9, 4, 6, 13],
               [4, 5, 12, -2]])

In [ ]:
## Dimension
M1.shape

(3, 4)

In [ ]:
M11 = tf.constant([[2, -5, -11, 0],
               [-9, 4, 6, 13],
               [4, 5, 12, -2]])

In [ ]:
## Dimension
M11.shape

TensorShape([3, 4])

In [ ]:
## how many ways
M11.ndim

2

In [ ]:
## NumPy
A = np.array([[2,1],
              [4,5]])
print(A) ## 2 x 2

B = np.array([[3,6],
              [7,9],
              [3,1]])
print(B) ## 3 x 2

[[2 1]
 [4 5]]
[[3 6]
 [7 9]
 [3 1]]


In [ ]:
## Matrix Multiplication
A.dot(B)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [ ]:
B.dot(A)

array([[30, 33],
       [50, 52],
       [10,  8]])

In [ ]:
import numpy as np
import tensorflow as tf

In [ ]:
A = np.array([  [6,4,24],
                [1,-9, 8]  ])

In [ ]:
A.shape

(2, 3)

In [ ]:
A

array([[ 6,  4, 24],
       [ 1, -9,  8]])

In [ ]:
## transpose
A.T

array([[ 6,  1],
       [ 4, -9],
       [24,  8]])

In [ ]:
A.transpose()

array([[ 6,  1],
       [ 4, -9],
       [24,  8]])

In [ ]:
## multiplying a matrix by itself
A.T.dot(A)

array([[ 37,  15, 152],
       [ 15,  97,  24],
       [152,  24, 640]])

In [ ]:
A.dot(A.T)

array([[628, 162],
       [162, 146]])

In [ ]:
A.T.shape

(3, 2)

In [ ]:
## Identity Matrix
## square matrix nxn
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
A.dot(I)

array([[ 6.,  4., 24.],
       [ 1., -9.,  8.]])

In [ ]:
A.T.dot(np.eye(2))

array([[ 6.,  1.],
       [ 4., -9.],
       [24.,  8.]])

In [ ]:
## Tensorflow
I = tf.eye(3)
I

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [ ]:
A

array([[ 6,  4, 24],
       [ 1, -9,  8]])

In [ ]:
## the rank is the number of independent columns (or rows) in a matrix
## the rank has to be based on the lowest value (cols or rows)
np.linalg.matrix_rank(A)

2

In [ ]:
## Matrix Inverse
## THe inverse cannot be computed for a DEPENDENT matrix
A = np.array([ [1,4,3],
               [2,4,6],
               [3,1,9.000001] ])

In [ ]:
np.linalg.matrix_rank(A) ## not FULL rank

3

In [ ]:
## determinant
## is zero if matrix is dependent
np.linalg.det(A)

-3.999999990789152e-06

In [ ]:
## inverse
## matrix is called SINGULAR when DEPENDENT or NOT FULL RANK
np.linalg.inv(A)

LinAlgError: Singular matrix

In [ ]:
## multicollinearity
## variances of the estimates get inflated
## the p-values are not trustworthy
## the estimates are inflated

200.0

In [ ]:
## SPARSE vs DENSE

A = np.array([ [1,0,0,1,0,0],
               [0,0,2,0,0,1],
               [0,0,0,2,0,0]])

In [ ]:
A

array([[1, 0, 0, 1, 0, 0],
       [0, 0, 2, 0, 0, 1],
       [0, 0, 0, 2, 0, 0]])

In [ ]:
import scipy.sparse as sparse

S = sparse.csr_matrix(A)
print(S)

  (0, 0)	1
  (0, 3)	1
  (1, 2)	2
  (1, 5)	1
  (2, 3)	2


In [ ]:
## change to dense
S.todense()

matrix([[1, 0, 0, 1, 0, 0],
        [0, 0, 2, 0, 0, 1],
        [0, 0, 0, 2, 0, 0]])

In [ ]:
## change to dense
S.toarray()

array([[1, 0, 0, 1, 0, 0],
       [0, 0, 2, 0, 0, 1],
       [0, 0, 0, 2, 0, 0]])

In [ ]:
## slicing
A

array([[1, 0, 0, 1, 0, 0],
       [0, 0, 2, 0, 0, 1],
       [0, 0, 0, 2, 0, 0]])

In [ ]:
A[0:2, 0:3]

array([[1, 0, 0],
       [0, 0, 2]])

In [ ]:
A

array([[1, 0, 0, 1, 0, 0],
       [0, 0, 2, 0, 0, 1],
       [0, 0, 0, 2, 0, 0]])

In [ ]:
X = np.array([  [[1,0,0,1,0,0],
               [0,0,2,0,0,1],
               [0,0,0,2,0,0]],

                [[1,0,0,1,0,0],
               [0,0,2,0,0,1],
               [0,0,0,2,0,0]],

                [[1,0,0,1,0,0],
               [0,0,2,0,0,1],
               [0,0,0,2,0,0]]
                ])

In [ ]:
X.shape

(3, 3, 6)